samples:
    S1:
        - ngs/S1_R1.fastq.gz
        - ngs/S1_R2.fastq.gz
    S2:
        - ngs/S2_R1.fastq.gz
        - ngs/S2_R2.fastq.gz
    S3:
        - ngs/S3_R1.fastq.gz
        - ngs/S3_R2.fastq.gz
    S4:
        - ngs/S4_R1.fastq.gz
        - ngs/S4_R2.fastq.gz
references:
    S1: hannover_isolates.fasta
    S2: hannover_isolates.fasta
    S3: munich_isolates.fasta
    S4: munich_isolates.fasta
references_bowtie2:
    S1: hannover_isolates
    S2: hannover_isolates
    S3: munich_isolates
    S4: munich_isolates
outdir: run_300322
bed:
maxdepth: 1000000
mark_short_splits: true